language: bash
os: linux


script:
 - sudo apt update
 - sudo apt install latexmk
 - latexmk Design.tex -pdf
 - latexmk API.tex -pdf
 - latexmk Glossary.tex -pdf
 - zip "1.$TRAVIS_BUILD_NUMBER StellarEngine.zip" *.pdf


deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  tag_name: 1.$TRAVIS_BUILD_NUMBER
  name: 1.$TRAVIS_BUILD_NUMBER StellarEngine
  file:
    - "1.$TRAVIS_BUILD_NUMBER StellarEngine.zip"
    - "Design.pdf"
    - "API.pdf"
    - "Glossary.pdf"
  skip_cleanup: true
  overwrite: true
  prerelease: true
  draft: false
  on:
    tags: false
    branch: master

