language: bash
os: linux


script:
 - sudo apt update
 - sudo apt install latexmk
 - latexmk Design.tex -pdf
 - latexmk API.tex -pdf


deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  tag_name: "1.StellarEngine"
  file:
    - "Design.pdf"
    - "API.pdf"
  skip_cleanup: true
  overwrite: true
